services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/gfos_db
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gfos_db
