name: Agda CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Agda
        run: |
          sudo apt-get update
          sudo apt-get install agda
      - name: Build Project
        run: agda --lib-file=financial-topos.agda-lib src/Kernel.lagda.md
